name: Android CI

on:
  push:
  
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21' # Change this based on your project needs

      - name: Grant Execute Permission for Gradle
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: List APK Directory
        run: ls -R app/build/outputs/apk/debug/  

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Upload APK to Testsigma
        run: |
          curl --location --request PUT "https://app.testsigma.com/api/v1/uploads/577" \
          --header "Authorization: Bearer ${{ secrets.TESTSIGMA_API_KEY }}" \
          --form "file=@app/build/outputs/apk/debug/app-debug.apk" \
          --form "name=MyApp" \
          --form "applicationId=215" \
          --form "version=123" \
          --form "uploadType=APK" \
          --form "description=Uploaded from GitHub Actions"    
